version: '3.1'

networks:
  traefik:
    external: true

  fake-btc-markets-backend:

services:
  api:
    image: "wexel/fake-btc-markets-api:${VERSION:-latest}"
    environment:
      DB_HOST: "${DB_HOST:-db}"
      DB_NAME: "${DB_NAME:-fake_btc_markets}"
      DB_PASS: "${DB_PASS:-4Me2Test}"
      DB_PORT: "${DB_PORT:-5432}"
      DB_USER: "${DB_USER:-fake_btc_markets}"
      PORT: '80'
      VERSION: "${VERSION:-latest}"
    networks:
      - traefik
      - fake-btc-markets-backend
    labels:
      - "traefik.http.middlewares.strip.stripprefix.prefixes=/fake-btc-markets"
      - "traefik.http.routers.fake-btc-markets.middlewares=strip@docker"
      - "traefik.http.routers.fake-btc-markets.rule=PathPrefix(`/fake-btc-markets`)"
      - "traefik.http.routers.fake-btc-markets.tls=true"
      - "traefik.http.routers.fake-btc-markets.tls.certresolver=myresolver"
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASS:-4Me2Test}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
    networks:
      - fake-btc-markets-backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure

  db-init:
    image: "wexel/fake-btc-markets-db-init:${VERSION:-latest}"
    environment:
      DB_HOST: "${DB_HOST:-db}"
      DB_NAME: "${DB_NAME:-fake_btc_markets}"
      DB_PASS: "${DB_PASS:-4Me2Test}"
      DB_PORT: "${DB_PORT:-5432}"
      DB_USER: "${DB_USER:-fake_btc_markets}"
      POSTGRES_PASS: "${POSTGRES_PASS:-4Me2Test}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
    networks:
      - fake-btc-markets-backend
    deploy:
      restart_policy:
        condition: none

volumes:
  postgres_data:
