version: '3.1'

networks:
  traefik:
    external: true

services:
  api:
    image: "wexel/fake-btc-markets-api:${VERSION:-latest}"
    environment:
      PORT: '80'
      VERSION: "${VERSION:-latest}"
    networks:
      - traefik
    labels:
      - "traefik.http.middlewares.strip.stripprefix.prefixes=/fake-btc-markets"
      - "traefik.http.routers.fake-btc-markets.middlewares=strip@docker"
      - "traefik.http.routers.fake-btc-markets.rule=PathPrefix(`/fake-btc-markets`)"
      - "traefik.http.routers.fake-btc-markets.entrypoints=https"
      - "traefik.http.routers.fake-btc-markets.tls.certresolver=myresolver"
    deploy:
      restart_policy:
        condition: on-failure
