name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Read file
        id: read_file
        run: echo "::set-output name=version::$(cat VERSION)"

      - name: Build
        run: bash "${GITHUB_WORKSPACE}/scripts/build.sh"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push
        run: bash "${GITHUB_WORKSPACE}/scripts/push.sh"

      - name: Deploy to swarm
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: ec2-user@aws.getwexel.com
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-swarm
          stack_file_name: docker/docker-stack.yml
          args: fake-btc-markets
        env:
          VERSION: ${{ steps.read_file.outputs.version }}
          COIN_API_KEY: ${{ secrets.COIN_API_KEY }}"
