name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build
        run: bash "${GITHUB_WORKSPACE}/scripts/build.sh"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push
        run: bash "${GITHUB_WORKSPACE}/scripts/push.sh"

      - name: Deploy to swarm
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: ssh://ec2-user@ec2-13-210-184-139.ap-southeast-2.compute.amazonaws.com
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-swarm
          stack_file_name: docker/docker-stack.yml
          args: fake-btc-markets
